name: Build and Deploy
on:
  push:
    branches:
      - proxy
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Install dependencies
        run: cd functions && yarn
      - name: Build
        run: cd functions && yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: functions
          path: functions
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
